"""Reading the game's own soundbanks: a sound name to decoded PCM samples.

The window has to preview what the map will actually play, and what the map
plays is the game's own samples. Nothing here ships them -- they belong to the
user's install and stay there -- so this reads them in place.

The chain is four lookups and one decoder:

    name --FNV-1 32--> event id --HIRC--> source id --DIDX/AKPK--> .wem
         --> RIFF fmt 0x0002 (Wwise IMA ADPCM) --> PCM16

Standard library only, and nothing internal. That is deliberate rather than
incidental: this module is about a file format and not about snapmap-midi, so
keeping it importable on its own is what makes promoting it out a directory
move instead of an untangling. It is also why there is no Oodle, no Vorbis, no
Opus and no native library anywhere below -- every embedded medium in these
banks is IMA ADPCM, and adding a dependency to decode formats that are not
present would buy nothing and cost the promotion.

Every constant here was measured against a retail install: 890 of 890 curated
palette sounds decode, the generated catalog enumerates every named Play event,
durations agree with the bank metadata, and piano notes land on equal
temperament. That matters because the plausible mistakes in this format do not
raise. They produce audio that is a little too long, or clicks once per frame,
or is a tritone off -- and still plays. The four that bite are called out at
the code they would break.
"""

from __future__ import annotations

import glob
import io
import os
import struct
import wave
import xml.etree.ElementTree as ET
from dataclasses import dataclass, replace

#: Where an install keeps its soundbanks, relative to the install root.
SOUND_SUBDIR = os.path.join("base", "sound", "soundbanks", "pc")

#: The generated event-name catalog beside the retail banks. Unlike HIRC,
#: this file keeps the authoring names and hierarchy needed by a sound browser.
EVENT_CATALOG_NAME = "soundbanksinfo.events"

#: The larger generated metadata catalog. It distinguishes Mixed events, whose
#: finite and infinite branches the compact event catalog cannot tell apart.
EVENT_XML_NAME = "soundbanksinfo.xml"

#: Bytes after the four strings in each soundbanksinfo.events record.
EVENT_RECORD_TRAILER_BYTES = 25

#: Localised voice banks loaded alongside the language-neutral retail banks.
DEFAULT_LANGUAGE = "English(US)"

#: The bank generator version every offset below was measured against. All 22
#: banks in the retail install carry it.
BANK_VERSION = 113

#: One ADPCM frame, per channel: a 4-byte header then 32 bytes of nibbles.
FRAME_BYTES = 0x24

#: Samples one frame yields. 64, not 65 -- see `decode_wwise_ima`.
SAMPLES_PER_FRAME = 64

#: The only `fmt` tag these banks use. Wwise writes its own IMA variant under
#: the number the RIFF registry gave to Microsoft ADPCM's neighbour, and the
#: two are not interchangeable: see `decode_wwise_ima`.
WWISE_IMA_FORMAT_TAG = 0x0002


class SoundsUnavailableError(RuntimeError):
    """Raised when there are no soundbanks to read at all.

    Means the install path is wrong, or points at something that is not a game
    install. Typed rather than a bare OSError because the window treats it as
    an ordinary state -- "no audio yet, here is how to get some" -- and not as
    a failure to report.
    """


class UnsupportedBankVersionError(ValueError):
    """Raised when a bank was generated by a Wwise version this has not seen.

    Loud on purpose. Every chunk offset, every payload layout and the sample
    count per frame are version-specific, and a later generator moved several
    of them. Reading a version 128 bank with these offsets would not fail --
    it would resolve plausible-looking rubbish and decode it into noise, which
    is far harder to diagnose than a refusal naming the version.
    """


@dataclass(frozen=True)
class SoundEvent:
    """One named Wwise event from the installed game's generated catalog."""

    event_id: int
    name: str
    path: str
    bus: str
    environment: str
    looping: bool
    duration_min: float
    duration_max: float


def parse_event_catalog(path) -> tuple[SoundEvent, ...]:
    """Read the generated named-event catalog beside the retail banks.

    HIRC stores only hashed object ids, so it cannot enumerate event names.
    The soundbanksinfo.events file is the game's own generated bridge between
    those ids and the Wwise authoring hierarchy. Its record count and ids are
    big endian, its string lengths are little endian, and its duration floats
    are big endian. Those mixed byte orders are part of the file format.
    """
    with open(path, "rb") as handle:
        data = handle.read()
    if len(data) < 4:
        raise ValueError("%s: event catalog is truncated before its record count" % path)

    count = struct.unpack(">I", data[:4])[0]
    cursor = 4
    events = []
    fields = ("name", "path", "bus", "environment")
    for record in range(count):
        if cursor + 4 > len(data):
            raise ValueError("%s: event catalog is truncated at record %d" % (path, record))
        event_id = struct.unpack(">I", data[cursor : cursor + 4])[0]
        cursor += 4
        strings = []
        for field in fields:
            if cursor + 4 > len(data):
                raise ValueError(
                    "%s: event catalog is truncated before %s in record %d" % (path, field, record)
                )
            size = struct.unpack("<I", data[cursor : cursor + 4])[0]
            cursor += 4
            if cursor + size > len(data):
                raise ValueError(
                    "%s: event catalog has an invalid %s length in record %d"
                    % (path, field, record)
                )
            try:
                value = data[cursor : cursor + size].decode("utf-8").rstrip("\x00")
            except UnicodeDecodeError as exc:
                raise ValueError(
                    "%s: event catalog has invalid UTF-8 in %s for record %d"
                    % (path, field, record)
                ) from exc
            strings.append(value)
            cursor += size

        end = cursor + EVENT_RECORD_TRAILER_BYTES
        if end > len(data):
            raise ValueError(
                "%s: event catalog is truncated in the trailer for record %d" % (path, record)
            )
        trailer = data[cursor:end]
        cursor = end
        duration_min, duration_max = struct.unpack(">ff", trailer[5:13])
        events.append(
            SoundEvent(
                event_id,
                strings[0],
                strings[1],
                strings[2],
                strings[3],
                bool(trailer[0]),
                duration_min,
                duration_max,
            )
        )
    # A small generated footer follows the declared records. It contains no
    # event entries, so parsing ends at the record count instead of guessing at
    # the footer's undocumented shape.
    return tuple(events)


def parse_looping_event_names(path) -> frozenset[str]:
    """Names whose generated Wwise duration type is Infinite or Mixed.

    The compact event catalog marks Infinite directly but collapses Mixed to
    the same bytes as ordinary one-shots. The XML overlay is therefore needed
    to prevent a mixed event's infinite branch from leaking a speaker emitter.
    ElementTree is streamed and cleared so the 26 MB retail file is never held
    as a second in-memory document.
    """
    looping = set()
    for _action, element in ET.iterparse(path, events=("end",)):
        if element.tag.rsplit("}", 1)[-1] == "Event":
            name = element.get("Name")
            if name and element.get("DurationType") in {"Infinite", "Mixed"}:
                looping.add(name.lower())
        element.clear()
    return frozenset(looping)


# ---------------------------------------------------------------- name hashing


def fnv1_32(name: str) -> int:
    """The Wwise object id for a name: FNV-1 32-bit over the lowercased name.

    FNV-**1**, not FNV-1a. The two differ only in the order of the multiply and
    the xor, they produce the same value for the empty string, and both look
    equally correct written down. Getting it backwards resolves nothing at all,
    which at least fails honestly -- but it is the first thing to check when a
    name that plainly exists cannot be found.

    Anchored by `fnv1_32("play_pianoc4") == 260642272`.
    """
    digest = 2166136261
    for byte in name.lower().encode("utf-8"):
        digest = ((digest * 16777619) & 0xFFFFFFFF) ^ byte
    return digest


# ------------------------------------------------------------------ containers


def parse_bnk(path) -> tuple:
    """A `.bnk` to (hirc objects, embedded media index).

    Returns `({object_id: (type, payload)}, {media_id: (absolute_offset, size)})`.
    The media offsets are made absolute against the DATA chunk here, so a
    caller never has to remember which of the two they are holding -- the
    relative form and the absolute form are both plain integers and mixing
    them reads a wrong region of a multi-hundred-megabyte file without error.

    A payload runs from the object id inclusive, because that is how the size
    field in front of it counts.
    """
    objects: dict = {}
    media: dict = {}
    data_offset = None
    hirc = None
    with open(path, "rb") as handle:
        while True:
            header = handle.read(8)
            if len(header) < 8:
                break
            tag, size = struct.unpack("<4sI", header)
            position = handle.tell()
            tag = tag.decode("ascii", "replace")
            if tag == "BKHD":
                _check_bank_version(path, handle.read(4))
            elif tag == "DIDX":
                block = handle.read(size)
                for i in range(size // 12):
                    media_id, offset, length = struct.unpack("<III", block[i * 12 : i * 12 + 12])
                    media[media_id] = (offset, length)
            elif tag == "DATA":
                data_offset = position
            elif tag == "HIRC":
                hirc = handle.read(size)
            handle.seek(position + size)
    if data_offset is not None:
        media = {m: (data_offset + o, s) for m, (o, s) in media.items()}
    if hirc:
        objects = _parse_hirc(hirc)
    return objects, media


def _check_bank_version(path, field: bytes) -> None:
    """Refuse a bank whose generator version is not the measured one."""
    if len(field) < 4:
        raise UnsupportedBankVersionError("%s: BKHD chunk is truncated" % path)
    version = struct.unpack("<I", field)[0]
    if version != BANK_VERSION:
        raise UnsupportedBankVersionError(
            "%s: soundbank version %d, expected %d -- every offset in this reader is "
            "version-specific and would silently misread" % (path, version, BANK_VERSION)
        )


def _parse_hirc(hirc: bytes) -> dict:
    """The HIRC chunk to {object id: (type, payload)}.

    Each record is a type byte, a u32 size, and then `size` bytes STARTING at
    the object id. The id is therefore inside the payload and not in front of
    it, which is why every offset in `resolve_sources` is four higher than the
    field lists in the format notes suggest.
    """
    objects = {}
    count = struct.unpack("<I", hirc[:4])[0]
    cursor = 4
    for _ in range(count):
        kind = hirc[cursor]
        size = struct.unpack("<I", hirc[cursor + 1 : cursor + 5])[0]
        object_id = struct.unpack("<I", hirc[cursor + 5 : cursor + 9])[0]
        objects[object_id] = (kind, hirc[cursor + 5 : cursor + 5 + size])
        cursor += 5 + size
    return objects


def parse_akpk(path) -> dict:
    """A `.pck` to {media_id: (path, absolute_offset, size)}.

    The stream table's offsets are stored scaled by a per-entry block size, so
    a raw `start` is a block index and not a byte position. An unscaled read
    lands within the first few megabytes of a two-gigabyte file and returns
    something that is not RIFF, which at least fails -- but only by luck.

    Returns {} rather than raising for a file that is not an AKPK, so a caller
    can point this at every `.pck` in a folder without pre-screening them.
    """
    with open(path, "rb") as handle:
        head = handle.read(8)
        if head[:4] != b"AKPK":
            return {}
        header_size = struct.unpack("<I", head[4:8])[0]
        handle.seek(0)
        buffer = handle.read(8 + header_size)
    cursor = 8
    _version, language_size, bank_size, _stream_size, _extern_size = struct.unpack(
        "<IIIII", buffer[cursor : cursor + 20]
    )
    cursor += 20
    cursor += language_size  # selected package path already scopes the language
    cursor += bank_size  # the soundbank table: banks are read directly instead
    entries = {}
    count = struct.unpack("<I", buffer[cursor : cursor + 4])[0]
    for i in range(count):
        base = cursor + 4 + i * 20
        media_id, block, size, start, _language = struct.unpack("<IIIII", buffer[base : base + 20])
        entries[media_id] = (path, start * block if block else start, size)
    return entries


# ------------------------------------------------------------- HIRC resolution

_TYPE_SOUND = 2
_TYPE_EVENT_ACTION = 3
_TYPE_EVENT = 4

#: Object types that hold children rather than a source of their own: the
#: random, sequence, switch, blend and actor-mixer containers.
_CONTAINERS = frozenset({5, 6, 7, 9, 10, 11, 12, 13})

#: How deep a container chain may nest before this gives up. Containers can
#: legally hold containers, and a malformed bank can hold a cycle; `seen`
#: catches the cycle and this catches the rest.
_MAX_DEPTH = 12


def _children(payload: bytes, valid) -> list:
    """A container's child list, found by shape rather than by offset.

    Container payloads carry a variable-length property block in front of the
    child list, so the list does not sit at a fixed offset and cannot be
    reached by counting. What is searched for instead is a u32 count followed
    by exactly that many ids that all name real objects in this bank -- a
    pattern a run of arbitrary bytes does not accidentally satisfy. The longest
    such run wins, because a short false positive is possible where a long one
    is not.
    """
    best = None
    for offset in range(4, len(payload) - 4):
        count = struct.unpack("<I", payload[offset : offset + 4])[0]
        if not (1 <= count <= 2000) or offset + 4 + count * 4 > len(payload):
            continue
        ids = struct.unpack("<%dI" % count, payload[offset + 4 : offset + 4 + count * 4])
        if all(i in valid for i in ids) and (best is None or count > best[0]):
            best = (count, ids)
    return list(best[1]) if best else []


def resolve_sources(objects, object_id: int, depth: int = 0, seen=None) -> list:
    """An object id to [(source media id, stream type), ...].

    An event names actions, an action names a target, and the target is either
    a sound or a container of them. Following that chain is the whole reason
    the HIRC is parsed at all: a sound name resolves to an event, and events
    hold no media.

    `seen` is not an optimisation. A switch container may name a sibling that
    names it back, and without it this recurses until the stack goes.
    """
    seen = seen if seen is not None else set()
    if object_id in seen or depth > _MAX_DEPTH or object_id not in objects:
        return []
    seen.add(object_id)
    kind, payload = objects[object_id]
    found: list = []
    if kind == _TYPE_EVENT:
        count = struct.unpack("<I", payload[4:8])[0]
        if 0 < count < 500 and 8 + count * 4 <= len(payload):
            for action in struct.unpack("<%dI" % count, payload[8 : 8 + count * 4]):
                found += resolve_sources(objects, action, depth + 1, seen)
    elif kind == _TYPE_EVENT_ACTION:
        found += resolve_sources(objects, struct.unpack("<I", payload[6:10])[0], depth + 1, seen)
    elif kind == _TYPE_SOUND:
        found.append((struct.unpack("<I", payload[9:13])[0], payload[8]))
    elif kind in _CONTAINERS:
        for child in _children(payload, objects):
            found += resolve_sources(objects, child, depth + 1, seen)
    return found


# ------------------------------------------------------------ Wwise IMA ADPCM

# The IMA step ladder and index table, unchanged since the original spec.
_STEP = [
    7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 23, 25, 28, 31, 34, 37, 41, 45,
    50, 55, 60, 66, 73, 80, 88, 97, 107, 118, 130, 143, 157, 173, 190, 209, 230,
    253, 279, 307, 337, 371, 408, 449, 494, 544, 598, 658, 724, 796, 876, 963,
    1060, 1166, 1282, 1411, 1552, 1707, 1878, 2066, 2272, 2499, 2749, 3024,
    3327, 3660, 4026, 4428, 4871, 5358, 5894, 6484, 7132, 7845, 8630, 9493,
    10442, 11487, 12635, 13899, 15289, 16818, 18500, 20350, 22385, 24623, 27086,
    29794, 32767,
]  # fmt: skip
_INDEX = [-1, -1, -1, -1, 2, 4, 6, 8, -1, -1, -1, -1, 2, 4, 6, 8]
_MAX_STEP_INDEX = len(_STEP) - 1


def decode_wwise_ima(data: bytes, channels: int, block_align: int) -> list:
    """Wwise IMA ADPCM to [[channel 0 samples], [channel 1 samples], ...].

    Four things here are wrong in every implementation that was reached for
    first, and not one of them raises. Each produces audio that plays.

    **A frame is 64 samples, not 65.** The 4-byte header holds a predictor that
    is emitted as sample 0, then only 63 of the 64 nibbles are consumed and the
    last is padding. Decoding all 64 gives 65 samples per frame: 1.56% long, a
    click at every frame boundary, and a pitch that drifts flat against the
    written sample rate. It sounds like a bad rip rather than like a bug.

    **The delta is the MUL form**, `((code & 7) * 2 + 1) * step >> 3`. The ADD
    form that the reference decoder and the standard library's `audioop` use --
    accumulating `step >> 3` plus conditional halves -- differs by a fraction of
    a step per sample. That integrates into audible roughness on sustained
    tones and nothing at all on short percussion, so it passes a spot check.

    **The low nibble comes first.** Reversed, the waveform is still a waveform;
    it is simply the wrong one, at roughly the right envelope.

    **Multichannel clusters whole frames**, `[ch0 36B][ch1 36B][ch0 36B]...`,
    not MS-IMA's 4-byte word interleave. Read as words, a stereo file decodes
    into two channels of alternating garbage that still has the right length
    and duration.

    `audioop` is not an option regardless: it was removed in Python 3.13, and
    it reads the high nibble first and uses the ADD form, so it is wrong on two
    of the four counts anyway.
    """
    if block_align != FRAME_BYTES * channels:
        raise ValueError(
            "unexpected blockAlign %d for %d channel(s); this decoder assumes %d bytes "
            "per channel per frame" % (block_align, channels, FRAME_BYTES)
        )
    out = [[] for _ in range(channels)]
    for index in range(len(data) // block_align):
        block = data[index * block_align : (index + 1) * block_align]
        for channel in range(channels):
            frame = block[channel * FRAME_BYTES : (channel + 1) * FRAME_BYTES]
            predictor, step_index = struct.unpack("<hB", frame[0:3])
            step_index = _clamp_index(step_index)
            samples = out[channel]
            samples.append(predictor)
            body = frame[4:]
            for i in range(SAMPLES_PER_FRAME - 1):  # the 64th nibble is padding
                byte = body[i >> 1]
                code = (byte >> 4) & 0xF if (i & 1) else byte & 0xF
                step = _STEP[step_index]
                delta = ((code & 7) * 2 + 1) * step >> 3
                predictor = predictor - delta if code & 8 else predictor + delta
                if predictor < -32768:
                    predictor = -32768
                elif predictor > 32767:
                    predictor = 32767
                step_index = _clamp_index(step_index + _INDEX[code])
                samples.append(predictor)
    return out


def _clamp_index(value: int) -> int:
    """Hold the step index inside the ladder.

    Clamped rather than wrapped or trusted: the index walks by up to 8 per
    sample and a header may carry any byte at all, so an unclamped read runs
    off the end of `_STEP` on ordinary content, not on corrupt content.
    """
    if value < 0:
        return 0
    return _MAX_STEP_INDEX if value > _MAX_STEP_INDEX else value


# ------------------------------------------------------------------- top level


class DoomSounds:
    """Named Play events and locally previewable media in one retail install.

    The language-neutral banks and one localised voice-bank directory are
    indexed in place. Mod banks outside the retail sound directory remain
    deliberately excluded until they have an explicit precedence contract.
    """

    def __init__(self, install_dir, language=DEFAULT_LANGUAGE):
        base = os.path.join(os.fspath(install_dir), SOUND_SUBDIR)
        if not os.path.isdir(base):
            raise SoundsUnavailableError(
                "no soundbanks under %s -- this does not look like a game install" % base
            )
        self.install_dir = install_dir
        self.sound_dir = base

        locale = None
        preferred = os.path.join(base, language) if language else None
        if preferred is not None and os.path.isdir(preferred):
            locale = preferred
        else:
            candidates = []
            for candidate in sorted(glob.glob(os.path.join(base, "*"))):
                if os.path.isdir(candidate) and (
                    glob.glob(os.path.join(candidate, "*.bnk"))
                    or glob.glob(os.path.join(candidate, "*.pck"))
                ):
                    candidates.append(candidate)
            locale = candidates[0] if candidates else None
        self.language = os.path.basename(locale) if locale is not None else None

        self.objects: dict = {}
        self.media: dict = {}
        banks = sorted(glob.glob(os.path.join(base, "*.bnk")))
        if locale is not None:
            banks += sorted(glob.glob(os.path.join(locale, "*.bnk")))
        for bank_path in banks:
            objects, media = parse_bnk(bank_path)
            self.objects.update(objects)
            for media_id, (offset, size) in media.items():
                self.media.setdefault(media_id, (bank_path, offset, size))

        self.stream: dict = {}
        packages = sorted(glob.glob(os.path.join(base, "*.pck")))
        if locale is not None:
            packages += sorted(glob.glob(os.path.join(locale, "*.pck")))
        for package_path in packages:
            self.stream.update(parse_akpk(package_path))

        self._events: tuple[SoundEvent, ...] | None = None
        self._event_by_name: dict[str, SoundEvent] = {}
        self._previewable_events: set[str] = set()
        self._loop_metadata_complete = False

    def _locate(self, media_id: int):
        """(path, offset, size) for a media id, or None when absent.

        A package copy wins over an embedded bank copy because the latter can
        be only the short prefetch stub for a streamed sound.
        """
        return self.stream.get(media_id) or self.media.get(media_id)

    def _media_locations(self, name: str) -> list:
        """Every unique available leaf medium named by an event."""
        locations = []
        seen = set()
        for media_id, _stream_type in resolve_sources(self.objects, fnv1_32(name)):
            location = self._locate(media_id)
            if location is None or media_id in seen:
                continue
            seen.add(media_id)
            locations.append((media_id, location))
        return locations

    def _media_location(self, name: str):
        """The first available medium named by an event.

        Wwise containers can list multiple sources. Some retail events have a
        missing first source and a valid later source, so availability is
        decided by the first source present in this install rather than by list
        position alone.
        """
        locations = self._media_locations(name)
        return locations[0][1] if locations else None

    def source_signature(self, name: str) -> list:
        """Small immutable media identity used by the numeric pitch cache."""
        signature = []
        for media_id, (path, offset, size) in self._media_locations(name):
            try:
                stamp = os.stat(path).st_mtime_ns
            except OSError:
                stamp = 0
            signature.append([media_id, int(offset), int(size), int(stamp)])
        return signature

    def names(self, candidates) -> set:
        """Which candidate event names this install can decode."""
        return {name for name in candidates if self._media_location(name) is not None}

    def event_catalog(self) -> tuple[SoundEvent, ...]:
        """Every named Play event declared by this installed game.

        The generated catalog is authoritative for event strings and authoring
        hierarchy. A Play event can still be an interactive-music graph, state
        transition, legacy/DLC reference, or another engine-only composite
        with no single medium to decode. Those remain valid map choices and are
        retained here; ``can_preview`` records the separate local-audio fact.
        Stop, Pause, Resume and Set events are controls rather than sounds and
        are deliberately excluded from the chooser.
        """
        if self._events is None:
            catalog_path = os.path.join(self.sound_dir, EVENT_CATALOG_NAME)
            if not os.path.isfile(catalog_path):
                self._events = ()
            else:
                xml_path = os.path.join(self.sound_dir, EVENT_XML_NAME)
                looping_names = frozenset()
                if os.path.isfile(xml_path):
                    try:
                        looping_names = parse_looping_event_names(xml_path)
                    except (OSError, ET.ParseError):
                        pass
                    else:
                        self._loop_metadata_complete = True
                events = []
                seen = set()
                for event in parse_event_catalog(catalog_path):
                    key = event.name.lower()
                    if not key.startswith("play_") or key in seen:
                        continue
                    seen.add(key)
                    if key in looping_names and not event.looping:
                        event = replace(event, looping=True)
                    if self._media_location(event.name) is not None:
                        self._previewable_events.add(key)
                    events.append(event)
                self._events = tuple(events)
            self._event_by_name = {event.name.lower(): event for event in self._events}
        return self._events

    def event(self, name: str) -> SoundEvent | None:
        """A named Play event, case-insensitively, or None."""
        self.event_catalog()
        return self._event_by_name.get(name.lower())

    def can_preview(self, name: str) -> bool:
        """Whether a named Play event resolves to one local audio medium."""
        self.event_catalog()
        return name.lower() in self._previewable_events

    def event_is_looping(self, name: str) -> bool | None:
        """Known loop behavior, or None without the complete XML overlay."""
        event = self.event(name)
        if event is None:
            return None
        if event.looping:
            return True
        return False if self._loop_metadata_complete else None

    @staticmethod
    def _decode_location(name: str, location) -> tuple:
        wem = _read_slice(location)
        if not wem or wem[:4] != b"RIFF":
            raise KeyError("%s: the media it names is not present in this install" % name)
        fmt, data = _riff_chunks(wem)
        if fmt is None or data is None:
            raise KeyError("%s: its media has no fmt or no data chunk" % name)
        tag, channels, rate, _bytes_per_second, align, _bits = struct.unpack("<HHIIHH", fmt[:16])
        if tag != WWISE_IMA_FORMAT_TAG:
            raise NotImplementedError(
                "%s: format tag 0x%04x, and only 0x%04x (Wwise IMA ADPCM) is decoded here"
                % (name, tag, WWISE_IMA_FORMAT_TAG)
            )
        return channels, rate, decode_wwise_ima(data, channels, align)

    def pcm_sources(self, name: str) -> list:
        """Every available event leaf as independently decoded PCM."""
        locations = self._media_locations(name)
        if not locations:
            raise KeyError("%s: no decodable Wwise media in these soundbanks" % name)
        decoded = []
        for media_id, location in locations:
            channels, rate, per_channel = self._decode_location(name, location)
            decoded.append(
                {
                    "media_id": media_id,
                    "channels": channels,
                    "rate": rate,
                    "per_channel": per_channel,
                }
            )
        return decoded

    def pcm(self, name: str) -> tuple:
        """A sound name to its first (channels, rate, per-channel samples)."""
        source = self.pcm_sources(name)[0]
        return source["channels"], source["rate"], source["per_channel"]

    def wav_bytes(self, name: str) -> bytes:
        """The sound as a complete little-endian PCM16 WAV, in memory."""
        channels, rate, per_channel = self.pcm(name)
        if channels == 1:
            flat = per_channel[0]
        else:
            flat = [
                per_channel[channel][index]
                for index in range(len(per_channel[0]))
                for channel in range(channels)
            ]
        buffer = io.BytesIO()
        with wave.open(buffer, "wb") as writer:
            writer.setnchannels(channels)
            writer.setsampwidth(2)
            writer.setframerate(rate)
            writer.writeframes(struct.pack("<%dh" % len(flat), *flat))
        return buffer.getvalue()


def _read_slice(location) -> bytes:
    """The bytes a (path, offset, size) triple names."""
    path, offset, size = location
    with open(path, "rb") as handle:
        handle.seek(offset)
        return handle.read(size)


def _riff_chunks(wem: bytes) -> tuple:
    """The `fmt ` and `data` payloads of a RIFF, or None for either that is absent."""
    cursor, fmt, data = 12, None, None
    while cursor + 8 <= len(wem):
        tag, size = struct.unpack("<4sI", wem[cursor : cursor + 8])
        tag = tag.decode("ascii", "replace")
        if tag == "fmt ":
            fmt = wem[cursor + 8 : cursor + 8 + size]
        elif tag == "data":
            data = wem[cursor + 8 : cursor + 8 + size]
            break
        # RIFF pads an odd-length chunk to an even boundary. Skipping only
        # `8 + size` past such a chunk lands one byte short and misaligns every
        # tag/size read after it, silently losing `fmt `/`data` further on.
        cursor += 8 + size + (size & 1)
    return fmt, data
